[project]
name = "pku-llma-hw"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipywidgets>=8.1.5",
    "jupyterlab>=4.4.0",
    "numpy>=2.2.4",
    "rich>=14.0.0",
    "termcolor>=3.0.1",
    "tiktoken>=0.9.0",
]
